name: dapp
description: Example application to create a mobile dapp
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  path: ^1.8.2

  # WalletConnect
  walletconnect_dart:
    path: ../../

  # Algorand
  algorand_dart: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
