name: mobile_dapp
description: An example how to create a mobile dApp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # WalletConnect
  walletconnect_dart:
    path: ../../

  # Algorand
  algorand_dart: ^1.0.3

  # Ethereum
  web3dart: ^2.4.1

  # URL Launcher
  url_launcher: ^6.1.5
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
